info:
  app:
    name: "Product Ms"
    description: "Microserviço que provê um catálogo de Produtos"
    version: 0.0.1
spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:store
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
server:
  port: 9999
